@TMod.Blog.Api_HostAddress = https://localhost:7095

// 查询所有配置项
GET {{TMod.Blog.Api_HostAddress}}/api/v1/admin/configurations

###

// 创建配置项 
POST {{TMod.Blog.Api_HostAddress}}/api/v1/admin/configurations
Content-Type: application/json

{
  "configurationKey":"TestKey",
  "configurationValue":"测试配置项"
}

###

// 根据 key 获取配置项
GET {{TMod.Blog.Api_HostAddress}}/api/v1/admin/configurations/TestKey

###

// 根据 key 删除配置项
DELETE {{TMod.Blog.Api_HostAddress}}/api/v1/admin/configurations/TestKey

###

// 根据 key 修改配置项
PATCH {{TMod.Blog.Api_HostAddress}}/api/v1/admin/configurations/TestKey
Content-Type: application/json

{
  "configurationValue":"TestValue"
}

###

// 根据 id 删除配置项
DELETE {{TMod.Blog.Api_HostAddress}}/api/v1/admin/configurations/id/2

###

// 根据 id 修改配置项
PATCH {{TMod.Blog.Api_HostAddress}}/api/v1/admin/configurations/id/2
Content-Type: application/json

{
  "configurationValue":"TestValue2"
}

###

// 根据 id 获取配置项
GET {{TMod.Blog.Api_HostAddress}}/api/v1/admin/configurations/id/2

###
