// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TMod.Blog.Infrastructure.CompiledModels
{
    public partial class TMod_Blog_RW_ContextModel
    {
        private TMod_Blog_RW_ContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("69ad0289-fd89-4f58-bed9-df8ff444ae83"), entityTypeCount: 8)
        {
        }

        partial void Initialize()
        {
            var articleTag = ArticleTagEntityType.Create(this);
            var article = ArticleEntityType.Create(this);
            var category = CategoryEntityType.Create(this);
            var comment = CommentEntityType.Create(this);
            var favorite = FavoriteEntityType.Create(this);
            var shareLink = ShareLinkEntityType.Create(this);
            var siteConfiguration = SiteConfigurationEntityType.Create(this);
            var tag = TagEntityType.Create(this);

            ArticleTagEntityType.CreateForeignKey1(articleTag, article);
            ArticleTagEntityType.CreateForeignKey2(articleTag, tag);
            ArticleEntityType.CreateForeignKey1(article, category);
            CategoryEntityType.CreateForeignKey1(category, category);
            CommentEntityType.CreateForeignKey1(comment, article);
            CommentEntityType.CreateForeignKey2(comment, comment);

            ArticleEntityType.CreateSkipNavigation1(article, tag, articleTag);
            TagEntityType.CreateSkipNavigation1(tag, article, articleTag);

            ArticleTagEntityType.CreateAnnotations(articleTag);
            ArticleEntityType.CreateAnnotations(article);
            CategoryEntityType.CreateAnnotations(category);
            CommentEntityType.CreateAnnotations(comment);
            FavoriteEntityType.CreateAnnotations(favorite);
            ShareLinkEntityType.CreateAnnotations(shareLink);
            SiteConfigurationEntityType.CreateAnnotations(siteConfiguration);
            TagEntityType.CreateAnnotations(tag);

            var functions = new Dictionary<string, IDbFunction>();
            var isSimilarTo = new RuntimeDbFunction(
                "TMod.Blog.Infrastructure.StringSimilarityExtensions.IsSimilarTo(string,string,double)",
                this,
                typeof(bool),
                "UDF_IsSimilarTo",
                schema: "dbo",
                storeType: "bit",
                methodInfo: typeof(StringSimilarityExtensions).GetMethod(
                    "IsSimilarTo",
                    BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly,
                    null,
                    new Type[] { typeof(string), typeof(string), typeof(double) },
                    null),
                scalar: true,
                nullable: true);

            var s1 = isSimilarTo.AddParameter(
                "s1",
                typeof(string),
                false,
                "nvarchar(max)");

            var s2 = isSimilarTo.AddParameter(
                "s2",
                typeof(string),
                false,
                "nvarchar(max)");

            var threshold = isSimilarTo.AddParameter(
                "threshold",
                typeof(double),
                false,
                "float");

            functions["TMod.Blog.Infrastructure.StringSimilarityExtensions.IsSimilarTo(string,string,double)"] = isSimilarTo;

            AddAnnotation("Relational:DbFunctions", functions);
            AddAnnotation("ProductVersion", "10.0.1");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
