// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using TMod.Blog.Infrastructure.CompiledModels;
using TMod.Blog.Infrastructure.Contextes;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(TMod_Blog_RW_Context), typeof(TMod_Blog_RW_ContextModel))]
